version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13.9-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
  smoke-tests:
    container_name: notranscoder-smoketests
    build: 
      dockerfile: SmokeTests.Dockerfile
      context: .
    links:
      - nginx