version: '2'
services:
  nginx:
    container_name: nginx
    image: openresty/openresty:xenial
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - test-server
  smoke-tests:
    container_name: notranscoder-smoketests
    build: 
      dockerfile: SmokeTests.Dockerfile
      context: .
    links:
      - nginx
  test-server:
    container_name: notranscoder-testserver
    build:
      dockerfile: TestServer.Dockerfile
      context: .